import type { Metadata } from "next";
import React from "react";

import Header from "components/layout/Header/Header";
import ThemeRegistry from "components/theme/ThemeRegistry";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body>
      <ThemeRegistry>
        <Header />
        {children}
      </ThemeRegistry>
    </body>
  </html>
);

export default RootLayout;
